config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get 'about', to: 'home#about'

  get 'rooms/search', to: 'rooms#search'
  get 'rooms/:id/reserve', to: 'rooms#reserve'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
 end

  resources :users, :only => [:show] do
    collection do
      get '/:id/favorites', to: 'users#favorites'
      get '/:id/myhotels', to: 'users#myhotels'
      get '/:id/myhotel/:hotel_id/myrooms', to: 'users#myrooms'
      get '/:id/myhotel/:hotel_id/contacts', to: 'users#contacts'
    end
  end

  resources :hotels, except: [:show] do
    resources :rooms do
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :reserves, only: [:index, :create, :destroy]
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/shared/_error_message.html.erb
<% if model.errors.any? %>
  <div class="alert alert-primary">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="flash alert-primary" role="alert">
  <%= flash[:notice] %>
</div>
<% end %>

<% if notice %>
<div class="flash alert-primary" role="alert">
  <p class="notice"><%= notice %></p>
</div>
<% end %>

<% if alert %>
<div class="flash alert-primary" role="alert">
  <p class="alert"><%= alert %></p>
</div>
<% end %>

app/views/layouts/shared/_footer.html.erb
<footer class="bg-light p-5 mt-5">
  <div class="container">
    <p class="float-right text-muted"><%= link_to "Page top", "#" %></p>
    <p class="float-left text-muted">©2021 Furuya Naoya · <%= link_to "Privacy", "#" %> · <%= link_to "Terms", "#" %></p>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top" >
    <div class="container-fluid">
      <%= link_to "Hoteresi", root_url, {class: "navbar-brand"} %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navmenu1" aria-controls="navmenu1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navmenu1">
        <div class="navbar-nav">
          <%= link_to "about", about_path, {class: "nav-item nav-link"} %>
          <%= link_to 'hotels',  hotels_path, {class: "nav-item nav-link"} %>
          <%= link_to 'rooms',  rooms_search_path, {class: "nav-item nav-link"} %>
          <% if user_signed_in? %>
            <%= link_to current_user.name, user_path(id: current_user.id), {class: "nav-item nav-link"} %>
          <% else %>
            <%= link_to "login", new_user_session_path, {class: "nav-item nav-link"} %>
            <%= link_to "sign up", new_user_registration_path, {class: "nav-item nav-link"} %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>