config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get 'about', to: 'home#about'

  get 'rooms/search', to: 'rooms#search'
  get 'rooms/:id/reserve', to: 'rooms#reserve'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
 end

  resources :users, :only => [:show] do
    collection do
      get '/:id/favorites', to: 'users#favorites'
      get '/:id/myhotels', to: 'users#myhotels'
      get '/:id/myhotel/:hotel_id/myrooms', to: 'users#myrooms'
      get '/:id/myhotel/:hotel_id/contacts', to: 'users#contacts'
    end
  end

  resources :hotels, except: [:show] do
    resources :rooms do
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :reserves, only: [:index, :create, :destroy]
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :room
  validates_uniqueness_of :room_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_room

  def create
    if @room.user_id != current_user.id
      @favorite = Favorite.create(user_id: current_user.id, room_id: @room.id)
    end
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, room_id: @room.id)
    favorite.destroy
  end

  private
  def set_room
    @room = Room.find(params[:room_id])
  end
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user_id: current_user.id, room_id: room.id) %>
  <%= link_to hotel_room_favorites_path(room_id: room.id, ), method: :post, remote: true, data: {"turbolinks" => false} do %>
    <button type="button" class="btn btn-secondary">
      LIKE登録 <span class="badge badge-light"><%= room.favorites.count %></span>
    </button>
  <% end %>
<% else %>
  <%= link_to hotel_room_favorites_path(room_id: room.id, id: room.favorites[0].id), method: :delete, remote: true, data: {"turbolinks" => false} do %>
    <button type="button" class="btn btn-primary">
      LIKE解除 <span class="badge badge-light"><%= room.favorites.count %></span>
    </button>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_<%= @room.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { room: @room }) %>");

app/views/favorites/destroy.js.erb
$("#favorite_<%= @room.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { room: @room }) %>");