config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get 'about', to: 'home#about'

  get 'rooms/search', to: 'rooms#search'
  get 'rooms/:id/reserve', to: 'rooms#reserve'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
 end

  resources :users, :only => [:show] do
    collection do
      get '/:id/favorites', to: 'users#favorites'
      get '/:id/myhotels', to: 'users#myhotels'
      get '/:id/myhotel/:hotel_id/myrooms', to: 'users#myrooms'
      get '/:id/myhotel/:hotel_id/contacts', to: 'users#contacts'
    end
  end

  resources :hotels, except: [:show] do
    resources :rooms do
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :reserves, only: [:index, :create, :destroy]
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :trackable, :timeoutable

  validates :name, presence: true
  validates :birthday, presence: true

  has_many :hotels, dependent: :destroy
  has_many :rooms
  has_many :favorites, dependent: :destroy
  has_many :reserves, dependent: :destroy

  def favorites_by?(room_id)
    favorites.where(room_id: room_id).exists?
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "Guest"
      user.birthday = "1990-01-01"
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i[update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

 def ensure_normal_user
   if resource.email == 'guest@example.com'
     redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません'
   end
 end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user
  before_action :set_user

  def show
  end

  def myhotels
    @hotels = Hotel.where(id: current_user.id).page(params[:page]).per(5).order('created_at DESC')
  end

  def myrooms
    @hotel = Hotel.find(params[:hotel_id])
    @rooms = Room.where(hotel_id: @hotel.id).page(params[:page]).per(5).order('created_at DESC')
  end

  def favorites
    favorites = Favorite.where(user_id: current_user.id).order(created_at: :desc).pluck(:room_id)
    likerooms = Room.find(favorites)
    @favorites = Kaminari.paginate_array(likerooms).page(params[:page]).per(5)
  end

  def contacts
    @reserves = Reserve.where(hotel_id: params[:hotel_id]).page(params[:page]).per(5).order('created_at DESC')
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_current_user
    if current_user.id != params[:id].to_i
      flash[:notice]="権限がありません"
      redirect_to :root
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_header_menu.html.erb
<div class="card-header bg-light">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "プロフィール", user_path(user.id), {class: "nav-item nav-link"} %>
        <%= link_to "お気に入り",  "/users/#{user.id}/favorites", {class: "nav-link nav-item"} %>
        <%= link_to "お問い合わせ内容", reserves_path, {class: "nav-link nav-item"} %>
        <%= link_to "マイホテル", "/users/#{user.id}/myhotels", {class: "nav-link nav-item"} %>
      </div>
    </div>
  </nav>
</div>

app/views/users/shared/_side_menu.html.erb
<ul class="list-group shadow-sm mb-3">
  <div class="list-group-item font-weight-bold bg-light text-muted">
    メニュー
  </div>
  <div class="list-group-item list-group-flush">
    <%= link_to "プロフィール", user_path(current_user.id), {class: "list-group-item list-group-item-action"} %>
    <%= link_to "お気に入り", "/users/#{user.id}/favorites", {class: "list-group-item list-group-item-action"} %>
    <%= link_to "お問い合わせ内容", reserves_path, {class: "list-group-item list-group-item-action"} %>
  </div>
</ul>
<ul class="list-group shadow-sm">
  <div class="list-group-item font-weight-bold bg-light text-muted">
    ホテル
  </div>
  <div class="list-group-item list-group-flush">
    <%= link_to "マイホテル", "/users/#{user.id}/myhotels", {class: "list-group-item list-group-item-action"} %>
    <%= link_to 'マイホテル登録', new_hotel_path(current_user.id), {class: "list-group-item list-group-item-action"} %>
  </div>
</ul>