config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get 'about', to: 'home#about'

  get 'rooms/search', to: 'rooms#search'
  get 'rooms/:id/reserve', to: 'rooms#reserve'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
 end

  resources :users, :only => [:show] do
    collection do
      get '/:id/favorites', to: 'users#favorites'
      get '/:id/myhotels', to: 'users#myhotels'
      get '/:id/myhotel/:hotel_id/myrooms', to: 'users#myrooms'
      get '/:id/myhotel/:hotel_id/contacts', to: 'users#contacts'
    end
  end

  resources :hotels, except: [:show] do
    resources :rooms do
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :reserves, only: [:index, :create, :destroy]
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :trackable, :timeoutable

  validates :name, presence: true
  validates :birthday, presence: true

  has_many :hotels, dependent: :destroy
  has_many :rooms
  has_many :favorites, dependent: :destroy
  has_many :reserves, dependent: :destroy

  def favorites_by?(room_id)
    favorites.where(room_id: room_id).exists?
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "Guest"
      user.birthday = "1990-01-01"
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i[update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

 def ensure_normal_user
   if resource.email == 'guest@example.com'
     redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません'
   end
 end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user
  before_action :set_user

  def show
  end

  def myhotels
    @hotels = Hotel.where(id: current_user.id).page(params[:page]).per(5).order('created_at DESC')
  end

  def myrooms
    @hotel = Hotel.find(params[:hotel_id])
    @rooms = Room.where(hotel_id: @hotel.id).page(params[:page]).per(5).order('created_at DESC')
  end

  def favorites
    favorites = Favorite.where(user_id: current_user.id).order(created_at: :desc).pluck(:room_id)
    likerooms = Room.find(favorites)
    @favorites = Kaminari.paginate_array(likerooms).page(params[:page]).per(5)
  end

  def contacts
    @reserves = Reserve.where(hotel_id: params[:hotel_id]).page(params[:page]).per(5).order('created_at DESC')
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_current_user
    if current_user.id != params[:id].to_i
      flash[:notice]="権限がありません"
      redirect_to :root
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/contacts.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-sm-3 d-none d-sm-block">
      <%= render 'users/shared/side_menu', user: @user %>
    </div>
    <div class="col-12 col-sm-9">
      <div class="card shadow-sm">
        <%= render 'users/shared/header_menu', user: @user %>
        <div class="card-body">
          <% unless @reserves.blank? %>
            <h4 class="text-left">ルーム問い合わせ一覧<span class="text-primary">(<%= @reserves.count %>)</span></h4>
          <% else %>
            <h4>ルームへの問い合わせはこちらに表示されます</h4>
          <% end %>
          <% @reserves.each do |reserve| %>
          <div class="card shadow-sm">
            <div class="card-body">
              <div class="row">
                <div class="col-6">
                  <h6 class="card-title"><%= reserve.room.hotel.hotel_name %>/<%= reserve.room.room_name %> / 問い合わせ ID:<%= reserve.id %></h6>
                  <p class="card-text">お問い合わせ内容: <span class="text-muted font-weight-bold"><%= reserve.contact.name %></p>
                    <p class="card-text">
                      契約について: <span class="text-muted font-weight-bold"><%= reserve.how_contract %></span> 日程: <span class="text-muted font-weight-bold"><%= reserve.contract %></span><br>
                      内見について: <span class="text-muted font-weight-bold"><%= reserve.how_preview %></span> 日程: <span class="text-muted font-weight-bold"><%= reserve.preview %></span><br>
                      希望入居日: <span class="text-muted font-weight-bold"><%= reserve.start_date %></span><br>
                      入居人数: <span class="text-muted font-weight-bold"><%= reserve.group %>人</span><br>
                    </p>
                  </div>
                  <div class="col-6">
                    <p class="card-text">備考<br><%= reserve.notes %></p>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= paginate @reserves %>
  </div>

app/views/users/favorites.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-sm-3 d-none d-sm-block">
      <%= render 'users/shared/side_menu', user: @user %>
    </div>
    <div class="col-12 col-sm-9">
      <div class="card shadow-sm">
        <%= render 'users/shared/header_menu', user: @user %>
        <div class="card-body">
          <% unless @favorites.blank? %>
          <h4 class="text-left">お気に入りルーム <small class="text-muted"><<%= @favorites.count %>件></small></h4>
          <% else %>
          <h4>お気に入りのルームを登録するとここに表示されます</h4>
          <% end %>
          <% @favorites.each do |favorite| %>
          <div class="card shadow-sm mb-3">
            <div class="row no-gutters">
              <div class="col-lg-7">
                <%= link_to (image_tag favorite.room_img.thumb.to_s, {width: "100%", class: "img-fluid"}),hotel_room_path(hotel_id: favorite.hotel_id, id: favorite.id)  %>
              </div>
              <div class="col-lg-5 my-auto">
                <div class="overflow-auto" style="width:100%; height:200px;">
                  <div class="card-body p-5">
                    <div class="text-right">
                      <small class="text-muted">下へスクロール</small>
                    </div>
                    <h6 class="card-title"><%= link_to favorite.room_name, hotel_room_path(hotel_id: favorite.hotel_id, id: favorite.id)%></h6>
                    <p class="card-text">賃料: ￥<%= favorite.price %><br>
                      最大人数: ￥<%= favorite.group %>人<br>
                      <% if favorite.smoke == "1" %>
                      禁煙
                      <% else %>
                      喫煙可
                      <% end %>
                    </p>
                    <p class="card-text">
                      <small class="text-muted">
                        <%= favorite.introduction %>
                      </small>
                    </p>
                    <div class="text-right pr-2">
                      <small class="text-muted">Update: <%= favorite.updated_at.strftime('%Y/%m/%d') %></small>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= paginate @favorites %>
</div>

app/views/users/myhotels.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-sm-3 d-none d-sm-block">
      <%= render 'users/shared/side_menu', user: @user %>
    </div>
    <div class="col-12 col-sm-9">
      <div class="card shadow-sm">
        <%= render 'users/shared/header_menu', user: @user %>
        <div class="card-body">
          <% unless @user.hotels.blank? %>
            <h4 class="text-left">マイホテル <%= link_to 'ホテル登録', new_hotel_path, {class: "btn btn-outline-primary"} %></h4>
          <% else %>
            <h4>マイホテルはありません <%= link_to 'ホテル登録', new_hotel_path, {class: "btn btn-outline-primary"} %></h4>
            <p class="text-muted">＊マイホテルは、ユーザーに提供するホテルを登録することで反映されます。<br>ホテルスタッフの方はボタンから登録してください。</p>
          <% end %>
          <% @user.hotels.each do |hotel| %>
          <div class="card my-3 shadow-sm">
            <div class="row no-gutters">
              <div class="col-lg-7 my-auto">
                <%= image_tag hotel.hotel_img.thumb.to_s, {width: "100%", class: "img-fluid"} %>
              </div>
              <div class="col-12 col-lg-5 my-auto">
                <div class="overflow-auto" style="width:100%; height:200px;">
                  <div class="card-body p-4">
                    <div class="text-right">
                        <small class="text-muted">下へスクロール</small>
                      </div>
                    <h5 class="card-title"><%= link_to hotel.hotel_name, hotel_rooms_path(hotel_id: hotel.id) %></h5>
                    <p class="card-text">Address: 〒<%= hotel.postcode.to_s.insert(3, "-") %><br>
                      <%= hotel.prefecture_name %><%= hotel.address_city %><%= hotel.address_street %></p>
                      <p class="card-text">
                        <% if hotel.preview == "1" %>
                          オンライン内見可
                        <% else %>
                          オンライン内見不可
                        <% end %><br>
                        <% if hotel.contract == "1" %>
                          オンライン契約可
                        <% else %>
                          オンライン契約不可
                        <% end %><br>
                        <% if hotel.parking == "1" %>
                          駐車場:有
                        <% else %>
                          駐車場:無
                        <% end %>
                      </p>
                      <div class="card-text">
                        <small class="text-muted"><%= hotel.introduction %></small>
                      </div>
                      <div class="text-right pr-2">
                        <small class="text-muted">Update: <%= hotel.updated_at.strftime('%Y/%m/%d') %></small>
                      </div>
                      <% if current_user.id == @user.id %>
                        <div>
                          <%= link_to "ホテル編集", edit_hotel_path(hotel.id), class:"pr-1" %>
                          <%= link_to "ルーム登録", new_hotel_room_path(hotel.id), class:"pr-1" %>
                        </div>
                        <div>
                          <%= link_to "ルーム一覧", "/users/#{@user.id}/myhotel/#{hotel.id}/myrooms", class:"pr-1" %>
                          <%= link_to "問い合わせ", "/users/#{@user.id}/myhotel/#{hotel.id}/contacts", class:"pr-1" %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= paginate @hotels %>
  </div>

app/views/users/myrooms.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-sm-3 d-none d-sm-block">
      <%= render 'users/shared/side_menu', user: @user %>
    </div>
    <div class="col-12 col-sm-9">
      <div class="card shadow-sm">
        <%= render 'users/shared/header_menu', user: @user %>
        <div class="card-body">
          <% unless @rooms.blank? %>
          <h4 class="text-left">ホテルルーム
            <%= link_to 'ルーム登録', new_hotel_room_path(@hotel.id), {class: "btn btn-outline-primary"} %>
          </h4>
          <% else %>
          <h4>ホテルルームはありません
            <%= link_to 'ルーム登録', new_hotel_room_path(@hotel.id), {class: "btn btn-outline-primary"} %>
          </h4>
          <p class="text-muted">＊ホテルルームは、ユーザーに提供するルームを登録することで反映されます。<br>ホテルスタッフの方はボタンから登録してください。</p>
          <% end %>
          <% @rooms.each do |room| %>
          <div class="card shadow-sm mb-3">
            <div class="row no-gutters">
              <div class="col-lg-7">
                <%= link_to (image_tag room.room_img.thumb.to_s, {width: "100%", class: "img-fluid"}),hotel_room_path(hotel_id: room.hotel_id, id: room.id)  %>
              </div>
              <div class="col-lg-5 my-auto">
                <div class="overflow-auto" style="width:100%; height:200px;">
                  <div class="card-body p-5">
                    <div class="text-right">
                      <small class="text-muted">下へスクロール</small>
                    </div>
                    <h6 class="card-title"><%= link_to room.room_name, hotel_room_path(hotel_id: room.hotel_id, id: room.id)%></h6>
                    <p class="card-text">賃料: ￥<%= room.price %><br>
                      最大人数: ￥<%= room.group %>人<br>
                      <% if room.smoke == "1" %>
                      禁煙
                      <% else %>
                      喫煙可
                      <% end %>
                    </p>
                    <p class="card-text">
                      <small class="text-muted">
                        <%= room.introduction %>
                      </small>
                    </p>
                    <div class="text-right pr-2">
                      <small class="text-muted">Update: <%= room.updated_at.strftime('%Y/%m/%d') %></small>
                    </div>
                    <% if current_user.id == @user.id %>
                    <%= link_to "ルーム編集", edit_hotel_room_path(@hotel.id, room.id), class:"pr-1" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= paginate @rooms %>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-sm-3 d-none d-sm-block">
      <%= render 'users/shared/side_menu', user: @user %>
    </div>
    <div class="col-12 col-sm-9">
      <div class="card">
        <%= render 'users/shared/header_menu', user: @user %>
        <div class="card-body shadow-sm">
          <div class="card my-3">
            <div class="card-body p-5 profile">
              <h5 class="card-title">プロフィール</h5>
              <p class="card-text">ユーザー名: <%= @user.name %></p>
              <p class="card-text">メールアドレス: <%= @user.email %></p>
              <p class="card-text">生年月日: <%= @user.birthday %></p>
              <%= link_to "編集",  edit_user_registration_path, {class: "lcard-link p-1"} %>
              <%= link_to "ログアウト", destroy_user_session_path, {class: "lcard-link p-1", method: :delete} %>
              <div class="text-right pr-3 ">
                <small class="text-muted">Update: <%= @user.updated_at.strftime('%Y/%m/%d') %></small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>